### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by SebastienForay**

### CODE REVIEW

**Comment by SebastienForay** [comment]
DO NOT MERGE

**Comment by SebastienForay** [comment]
@cloudkucooland First test with Crowdin to translate files, it removes empty lines in Telegram.tg but we can maybe replace it with a < br > tag, if Telegram handles it

**Comment by cloudkucooland** [comment]
> @cloudkucooland First test with Crowdin to translate files, it removes empty lines in Telegram.tg but we can maybe replace it with a
> tag, if Telegram handles it

We can use < br > and I can force all messages to be HTML. Our choices for Telegram are HTML or Markdown.

Is it clear what is template coding {{}} vs. translatable strings? 

https://gowebexamples.com/templates/ might be useful for people ?

**Comment by SebastienForay** [comment]
> > @cloudkucooland First test with Crowdin to translate files, it removes empty lines in Telegram.tg but we can maybe replace it with a
> > tag, if Telegram handles it
> 
> We can use < br > and I can force all messages to be HTML. Our choices for Telegram are HTML or Markdown.
> 
> Is it clear what is template coding {{}} vs. translatable strings?
> 
> https://gowebexamples.com/templates/ might be useful for people ?

Everything between { } are considered variables by Crowdin and users are asked to NOT translate it.

**Comment by SebastienForay** [comment]
Capture d’écran 2022-01-05 à 19 37 14

**Pull request merged**
